package com.example.debuglib

import io.realm.RealmObject
import io.realm.annotations.PrimaryKey
import io.realm.annotations.RealmClass

@RealmClass
open class Person(

    var ID : Int = 0,
    var name: String? = null

) : RealmObject() {

    // Standard getters & setters generated by your IDE…


    open fun addname(input : String?= null){
        this.name = input
    }

    open fun setId(id : Int ?= null){
        this.ID = id!!
    }

    open fun getId():Int{
        return ID
    }

    open fun update(id:Int){
        this.ID = id
    }

}